### ISSUE TITLE
Os endpoints não retornam o label da categoria

### ISSUE THREAD

**Issue by thiagoabreudev** [ecomclub/market#12]
O response de /v1/applications e /v1/applications/:app_id retorna apenas o slug da categoria. Seria muito bom se eles pudessem retornar também o label da categoria, para que isso seja mostrado nos componentes implementados em  [admin-marketplace](https://github.com/ecomclub/admin-marketplace). 

Isso é possível?

**Comment by talissonf** [comment]
@thiagoabreudev Infelizmente não é possível porque as categorias são cadastradas assim no db, apenas com o slug. O que você pode ta fazendo é criar um dicionário para as categorias, até por que o admin poderá ser acessado tanto em pt_br quanto em en_us.  Aqui o [dicionário](https://github.com/ecomclub/market/blob/master/src/Market/Services/Dictionary.php) que eu uso no site do market para as [categorias](https://github.com/ecomclub/market/blob/master/src/Market/Services/Categories.php).

**Comment by thiagoabreudev** [comment]
Ok, @talissonf , sem problema.
Obrigado!

**Comment by leomp12** [comment]
@talissonf seria legal ter um endpoint para as categorias, tipo este aqui para segmentos de lojas:
https://e-com.plus/api/v1/segments.json
mas em vez do `id` você teria o `slug`

**Comment by talissonf** [comment]
@leomp12 @thiagoabreudev  Posso implementar o endpoint para as categorias.

**Comment by talissonf** [comment]
Endpoint implementado https://market.e-com.plus/v1/categories ou  https://market.e-com.plus/v1/categories/sales
