### ISSUE TITLE
Login de parceiro não funciona (?)

### ISSUE THREAD

**Issue by leomp12** [ecomclub/market#21]
Não consigo logar, aparecem dois checks (um em cada input) mas nada mais acontece.
Também não consigo recuperar senha, como devo fazer @talissonf ? Isto está funcional?

**Comment by talissonf** [comment]
O Login funciona normalmente, você que não tem cadastro no market e o cadastro não é feito via market. Lembro que o vitor criou pra mim esse login e depois eu criava a senha e o cadastro no market mas não cheguei a implementar isso :confused: .
Vou implementar o cadastro e a recuperação de senha.

**Comment by leomp12** [comment]
O @vitorrgg criou uma conta pra mim, mas realmente eu não cadastrei a senha, até procurei por isto, mas como não foi implementado...
Além disto, o formulário de login deveria responder com uma mensagem que descrevesse o problema, reportando que o cadastro não existe ou a senha está incorreta ou falta adicionar uma senha, certo?

**Comment by talissonf** [comment]
> Além disto, o formulário de login deveria responder com uma mensagem que descrevesse o problema, reportando que o cadastro não existe ou a senha está incorreta ou falta adicionar uma senha, certo?

SIM!

**Comment by talissonf** [comment]
@leomp12 eu implementei a criação da senha do parceiro, ta no mesmo modal de login como `Primeiro acesso? criei seu login.`
Vou manter o issue aberto porque implementei só pra voce usar agora, to resolvendo outros issues reportados pelo matheus e pelo vitor em outros apps e quando terminar foco nesses ajustes do market.

**Comment by leomp12** [comment]
@talissonf o link para "criar senha" até apareceu, mas ele não fez nada diferente do formulário de login, nada aconteceu...
No console tem um `Request login fail.`

**Comment by leomp12** [comment]
Só pra confirmar, o partner está cadastrado com o ID 153 no e-mail leonardo@e-com.club, tento criar a senha com o mesmo e-mail, mas não rola

**Comment by talissonf** [comment]
Vou olhar aqui, mas eu acho que meu id de cadastro também é 153 :thinking:

**Comment by leomp12** [comment]
O seu é 152:

![index](https://user-images.githubusercontent.com/10326572/73490340-0e70a580-438b-11ea-8952-d2560aaf521c.jpg)

**Comment by talissonf** [comment]
Tenta agora, acho que vai rolar

**Comment by leomp12** [comment]
Agora deu pra logar, valeu.
Em algum lugar em consigo cadastrar o app com o JSON em vez de preencher o formulário campo a campo?
Se não, tem como você colocar por favor, nem que seja só um textarea pra jogar tudo junto? Com exceção dos campos exclusivos do Market é claro.

**Comment by leomp12** [comment]
Ou melhor, PUT na API para criar app ou atualizar se já existir, tem isto ainda que interno?
Aí eu criaria um workflow pra CI.

**Comment by leomp12** [comment]
@vitorrgg tô achando que vou deixar esse cadastri é proc :grinning:

**Comment by leomp12** [comment]
@talissonf isso pode ser fechado?

**Comment by talissonf** [comment]
Sim
